// angular-app/src/app/app.component.ts
import { Component } from '@angular/core';
import { AngularFireFunctions } from '@angular/fire/functions';
import { AngularFireAuth } from '@angular/fire/auth';
import * as firebase from 'firebase/app';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent {
  constructor(public afAuth: AngularFireAuth, private fun: AngularFireFunctions) {}



  loginWithGoogle() {
    this.afAuth.auth.signInWithPopup(new firebase.auth.GoogleAuthProvider());
  }

  sendEmail() {
    const callable = this.fun.httpsCallable('genericEmail');
    callable({ text: 'Sending email with Angular and SendGrid is fun!', subject: 'Email from Angular'}).subscribe();
  }
}

<h2>SendGrid Transactional Email with Angular</h2>


<div *ngIf="(afAuth.authState | async) as user; else login;">

    {{ user | json }}

    <hr>

    <button (click)="sendEmail()">Send Email with Callable Function</button>
    <button (click)="afAuth.auth.signOut()">SignOut</button>

  
</div>

<ng-template #login>
  <button (click)="loginWithGoogle()">SignIn with Google</button>
</ng-template>

// svelte-app/src/App.svelte
<script>
	import firebase from 'firebase/app';
	import { auth, functions } from './firebase';
	import { onMount } from 'svelte';

	let user = null;

	onMount(async () => {
		auth.onAuthStateChanged(u => user = u);
	});

	function sendEmail() {
		const callable = functions.httpsCallable('genericEmail');
		return callable({ text: 'Sending email with Svelte and SendGrid is fun!', subject: 'Email from Svelte'}).then(console.log);
	}
	
</script>
<h2>SendGrid Transactional Email with Svelte</h2>

{#if user}
	<p>{ JSON.stringify(user) }</p>
    <button on:click={() => sendEmail()}>Send Email with Callable Function</button>
    <button on:click={() => auth.signOut()}>SignOut</button>

{:else}
	<button on:click={() => auth.signInWithPopup(new firebase.auth.GoogleAuthProvider())}>SignIn with Google</button>
{/if}
